-- MySQL Script generated by MySQL Workbench
-- 07/13/16 23:42:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SEGURIDAD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SEGURIDAD` ;

-- -----------------------------------------------------
-- Schema SEGURIDAD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SEGURIDAD` DEFAULT CHARACTER SET utf8 ;
USE `SEGURIDAD` ;

-- -----------------------------------------------------
-- Table `SEGURIDAD`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEGURIDAD`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `SEGURIDAD`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `tipo` CHAR(4) NOT NULL,
  `estado` CHAR(4) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SEGURIDAD`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `SEGURIDAD`;
INSERT INTO `SEGURIDAD`.`Usuario` (`idUsuario`, `email`, `password`, `tipo`, `estado`) VALUES (DEFAULT, 'admin@admin.com', 'admin1234', '0009', '0000');

COMMIT;

